# docker-compose.yml
version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: voting_postgres
    environment:
      POSTGRES_DB: voting
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - voting_network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: voting_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - voting_network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: voting_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
    networks:
      - voting_network

volumes:
  postgres_data:

networks:
  voting_network:
    driver: bridge
